quarkus.application.name=parkventory-backend
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.methods=GET,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,Idempotency-Key
quarkus.http.cors.access-control-allow-credentials=true
%prod.quarkus.http.cors.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${PARKVENTORY_DB_USER:parkventory}
quarkus.datasource.password=${PARKVENTORY_DB_PASSWORD:parkventory-local-only}
%dev.quarkus.datasource.jdbc.url=${PARKVENTORY_JDBC_URL:jdbc:postgresql://localhost:5434/parkventory}
%prod.quarkus.datasource.jdbc.url=${PARKVENTORY_JDBC_URL:jdbc:postgresql://localhost:5434/parkventory}
quarkus.flyway.migrate-at-start=true
%prod.quarkus.flyway.migrate-at-start=false
quarkus.flyway.validate-on-migrate=true
quarkus.hibernate-orm.schema-management.strategy=none

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=${PARKVENTORY_TEST_POSTGRES_IMAGE:docker.io/library/postgres:18.3-alpine@sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7}
%test.parkventory.test.expected-postgres-version=${PARKVENTORY_TEST_POSTGRES_VERSION:18.3}
%test.quarkus.http.test-port=0

quarkus.mailer.from=Parkventory <no-reply@parkventory.local>
quarkus.mailer.host=${PARKVENTORY_SMTP_HOST:127.0.0.1}
quarkus.mailer.port=${PARKVENTORY_SMTP_PORT:1025}
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.tls=false
%dev.quarkus.mailer.mock=false
%prod.quarkus.mailer.mock=false
%test.quarkus.mailer.mock=true
%prod.quarkus.mailer.from=${PARKVENTORY_SMTP_FROM}
%prod.quarkus.mailer.host=${PARKVENTORY_SMTP_HOST}
%prod.quarkus.mailer.port=${PARKVENTORY_SMTP_PORT}
%prod.quarkus.mailer.username=${PARKVENTORY_SMTP_USERNAME}
%prod.quarkus.mailer.password=${PARKVENTORY_SMTP_PASSWORD}
%prod.quarkus.mailer.start-tls=REQUIRED

parkventory.web.base-url=${PARKVENTORY_WEB_BASE_URL:http://127.0.0.1:5173}
parkventory.auth.magic-link-minutes=15
parkventory.auth.session-days=7
parkventory.outbox.poll-interval=1s
parkventory.migration-only=${PARKVENTORY_MIGRATION_ONLY:false}
parkventory.cookie.secure=false
%prod.parkventory.cookie.secure=true

quarkus.smallrye-openapi.info-title=Parkventory API
quarkus.smallrye-openapi.info-version=0.2.0
quarkus.smallrye-openapi.info-description=API locale persistante pour le partage de places de parking entre collègues.
quarkus.swagger-ui.always-include=true
%prod.quarkus.swagger-ui.always-include=false

quarkus.log.category."com.parkventory".level=INFO
quarkus.log.category."quarkus-mailer".level=WARN
