/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false worker/worker-configuration.d.ts` (hash: 81430f1f7284eda6dc3ba2535f8a59a4)
interface __BaseEnv_Env {
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	APP_ENV: "production";
	EMAIL_FROM: "Parkventory <noreply@parkventory.com>";
	PUBLIC_ORIGIN: "https://parkventory.com";
	APP_SECRET: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "EMAIL_FROM" | "PUBLIC_ORIGIN" | "APP_SECRET" | "TURNSTILE_SECRET_KEY">> {}
}
